services:
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:8080
    volumes:
      - ./backend/api:/app/api
      - ./backend/machine_learning:/app/machine_learning
      - ./backend/.vscode:/app/.vscode
    tty: true
    stdin_open: true
    depends_on:
      - postgresql
    networks:
      - project-network
    deploy:
      resources:
        # limits:
        #   memory: 12G
        #   cpus: '4.0'
        reservations:
          # memory: 4G
          # cpus: '2.0'
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  postgresql:
    image:  postgres:17.6
    container_name: postgresql
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

  adminer:
    image: adminer:5.3.0-standalone
    container_name: adminer
    environment:
      - ADMINER_DESIGN=pepa-linha # https://www.adminer.org/en/#extras:~:text=set%2C%205.%20Size.-,Alternative%20designs,-hever
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgresql
    networks:
      - project-network

volumes:
  postgres_data:
    driver: local

networks:
  project-network:
    driver: bridge