services:
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:8080
    volumes:
      - ./backend/webapps:/app/tomcat/webapps
      - ./backend/python:/app/python
      - ./backend/src:/app/src
      - ./backend/.vscode:/app/.vscode
    tty: true
    stdin_open: true
    depends_on:
      - postgresql
    networks:
      - project-network

  postgresql:
    image:  postgres:17.6
    container_name: postgresql
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

  adminer:
    image: adminer:4.17.1-standalone
    container_name: adminer
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgresql
    networks:
      - project-network

volumes:
  postgres_data:
    driver: local

networks:
  project-network:
    driver: bridge